# Generated by Django 3.1.1 on 2021-02-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
