# Generated by Django 3.1.1 on 2021-02-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_area',
            options={'managed': True},
        ),
    ]
